### ISSUE TITLE
Question: Encrypted filenames

### ISSUE THREAD

**Issue by Dr-Nuke** [AGWA/git-crypt#196]
Hey,
I saw the "limitations" of git-crypt explicitly state that file names are not encrypted. 
Is this something that got excluded or might be done at some point? Are there any plans?
Thanks for the reply!

**Comment by AGWA** [comment]
This limitation is inherent to how git-crypt works (more generally, how git filters work).  Filenames will never be encrypted with git-crypt.

git-crypt is intended to encrypt a handful of secret files in an otherwise public repository, and it makes technical tradeoffs to make this use care easy, at the cost of things like filename encryption.  If you care about filenames being encrypted, it suggests that git-crypt is not the best solution for your use case.

**Comment by Dr-Nuke** [comment]
thanks for the info.
