### ISSUE TITLE
eclipse: git-crypt filter stopped working

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [AGWA/git-crypt#205]
please see: https://bugs.eclipse.org/bugs/show_bug.cgi?id=561666

**Comment by alerque** [comment]
I don't see how this is a git-crypt issue. Per your own report linked above it continues to work just fine from the CLI and nothing has changed on this end. In fact also per your own report it works fine if you call in properly from inside Eclipse too, you were just doing something weird before quoting the binary name. That should never have been necessary and could easily cause problems with path resolution.

By the way if your PATH is setup properly you can call it as either `git-crypt ...` or `git crypt ...`.

This issue should be closed, there doesn't seem to be anything to do here. A change to how Eclipse handles path resolution and quoting is irrelevant here.

**Comment by Andrei-Pozolotin** [comment]
can you please link here git spec on config filter entry format: why quoting is needed

**Comment by alerque** [comment]
Quoting is used just like anywhere in a shell: to avoid issues if the path includes a space or other special characters. Rather than checking the resolved binary name and path for issues, it just quotes it by default to be safe. This should be just fine. Whatever Eclipse is doing is wrong, they should handle this as an already ready to use shell command the way POSIX would handle it, not try to add more escaping.

**Comment by Andrei-Pozolotin** [comment]
confirmed by eclipse, thank you.
