### ISSUE TITLE
Improve usability/documentation with untrusted GPG keys

### ISSUE THREAD

**Issue by BrendanThompson** [AGWA/git-crypt#23]
Hey @AGWA having a weird issue when I'm trying to add my GPG key, i get the following

```
gpg: <Key ID>: There is no assurance this key belongs to the named user
gpg: [stdin]: encryption failed: Unusable public key
git-crypt: GPG error: Failed to encrypt
```

Any ideas on that one matey?

**Comment by dupuy** [comment]
I had this issue ("There is no assurance this key belongs to the named user") when I started using the GPG keys feature, and I suspect that pretty much anyone who tries to use git-crypt with GPG keys will run into it sooner or later.  My first guess was that the user who generated the key had somehow forgotten to sign it, but of course the problem was that _I_ hadn't signed it; this needs to be in the documentation (probably the README) and perhaps in the error handling code as well (i.e. if gpg command fails then suggest to the user that they may need to sign the key that they are trying to add).

**Comment by AGWA** [comment]
Ah, thanks for reminding me about this issue @dupuy.  Last week I added a `--trusted` option to `git-crypt add-gpg-user`.  If you use it, it will add the user even if their key isn't trusted by GPG.  I would like it if git-crypt could output a helpful error message informing the user of the `--trusted` option, but unfortunately GPG doesn't use a unique exit status for an untrusted key, so I would have to either output the message upon any GPG error, even if it's not relevant, or attempt to parse stderr.  Documenting this in the README is also a very good idea.

**Comment by pfalcon** [comment]
I read this ticket, #39, #47 - and they not only cover issues with git-crypt I immediately spotted during initial testing of git-crypt, but also offer comprehensive discussion, and good plan for solutions. And... nothing. Perhaps, at this point, user pull request should be coming in. But having so many obvious issues not resolved makes one wonder if the overall approach is sound and if someone better be using something like git-remote-gcrypt . So, @AGWA, what's happening with git-crypt - do you maintain it, or may I imagine that you fell out of love with it, with having so many unresolved issues?

**Comment by BrendanThompson** [comment]
Going to close this off, as there is seemingly no resolution in sight.
