### ISSUE TITLE
Allow users to use GPG private keys as keyfiles

### ISSUE THREAD

**Issue by dlo** [AGWA/git-crypt#3]

**Comment by davidak** [comment]
what if i use gpg to encrypt my gpg private key in an dotfiles repository? i think i will not be able to encrypt it, right?

**Comment by AGWA** [comment]
@davidak wrote:
> what if i use gpg to encrypt my gpg private key in an dotfiles repository? i think i will not be able to encrypt it, right?

If you're using git-crypt with GPG mode to encrypt your GPG private key, then yeah, you won't be able to unlock your repo should you lose all copies of the unencrypted version.  Not a great idea ;-).  This sounds like a good use case for passphrase-based encryption, which I just opened an issue for (#75).

In any case, this would be better discussed on the [mailing list](https://lists.cloudmutt.com/mailman/listinfo/git-crypt-discuss) or in a separate issue, rather than this old closed issue.
