### ISSUE TITLE
File modes not preserved

### ISSUE THREAD

**Issue by stevenringo** [AGWA/git-crypt#46]
Files with 600 permission are being committed to the repo with 644 permission.

Have tried changing the permission to both encrypted and decrypted files to no avail.

**Comment by AGWA** [comment]
@stevenringo Git doesn't track file permissions, except for the execute bit, so this is expected behavior whether or not you're using git-crypt.

Git does respect your umask, and also has the `core.sharedRepository` config option, if you need your work tree to have restrictive permissions.

**Comment by stevenringo** [comment]
Thanks for the prompt reply. I had made an incorrect assumption.

**Comment by Urie96** [comment]
> Git doesn't track file permissions, except for the execute bit, so this is expected behavior whether or not you're using git-crypt.
> 
> Git does respect your umask, and also has the `core.sharedRepository` config option, if you need your work tree to have restrictive permissions.

@AGWA  Would you consider adding an option for git-crypt to write decrypted files with 0600 permissions by default? Since Git only tracks the executable bit and not full file modes, sensitive files may be checked out as 0644 in the working tree after decryption. For secrets, a safer default would be very helpful.
