### ISSUE TITLE
Running `git-crypt init` on an already initialized repository renders the data unreadable

### ISSUE THREAD

**Issue by bhourigan** [AGWA/git-crypt#78]
If you accidentally run git-crypt init on an already initialized repository it is destructive and renders any encrypted data unreadable. A good habit is to run `git-crypt status` before running init, but it's easy to make this mistake. It would be nice if git-crypt warns you if the repository is already initialized. Bonus if git-crypt requires an additional argument such as --force to clobber what's already in place.

**Comment by AGWA** [comment]
`git-crypt init` already checks for an initialized repository:

```
$ mkdir test
$ cd test
$ git init
Initialized empty Git repository in /tmp/test/.git/
$ git-crypt init
Generating key...
$ git-crypt init
Error: this repository has already been initialized with git-crypt.
```

Do you remember the sequence of steps you took that resulted in your git-crypt state being clobbered?

**Comment by bhourigan** [comment]
@AGWA You are absolutely right, apologies for the misfile. I reviewed my shell history and I was unable to reproduce it, but it's happened to me twice now. I'll keep playing with it and reopen once I have a reliable set of steps to reproduce the issue. FWIW, when it breaks, this is the output from `git-crypt unlock`:

```
git-crypt: error: encrypted file has been tampered with!
error: external filter "git-crypt" smudge failed 1
error: external filter "git-crypt" smudge failed
fatal: xxx: smudge filter git-crypt failed
Error: 'git checkout' failed
git-crypt has been set up but existing encrypted files have not been decrypted
```

**Comment by prafullat** [comment]
What is solution for this problem? I am getting same error for my repository.

**Comment by bhourigan** [comment]
I had a lot of problems with git-crypt and suffered data loss multiple times. I gave up identifying the root cause and switched to sops.

**Comment by JonathanSerafini** [comment]
Seems like you can accomplish this as follows : 

```
mkdir crypt-init-test
cd crypt-init-test
git init .
echo 0 > 0
git add 0
git commit -m 0
git-crypt init 
git-crypt init   # will fail, and rightfully so
git-crypt lock # locking will allow init to succeed
git-crypt init
```

At this point your repo's hosed because you've overwritten the shared encryption key... However this isn't a permanent problem.

As far as I can tell, the difference between a locked and unlock repository is the presence of .git/git-crypt/keys/default ( the un-encrypted version of the shared key ) which isn't committed into your git repository. You'll notice that what git-crypt specific bits *do* get committed are .git-crypt/keys which are the GPG encrypted versions of the shared encryption keys. And those will not get overridden unless you specifically act upon the individual keys.

If you do `git-crypt init` your working directory you'll be able to restore the encryption key from one of the committed ones. Mind you you'll need a clean working directory though so you my want to copy anything you were working on elsewhere ...

```
git-crypt lock
git-crypt init   # oh noes
git status        # files that were encrypted now all appear to be modified
gpg --output .git/git-crypt/keys/default --decrypt .git-crypt/keys/default/0/<some hash>.gpg
git status .      # files still appear modified -_-
git checkout -f * # clean working directory
git-crypt unlock 
```

**Comment by agconti** [comment]
Thanks @JonathanSerafini this worked for me.
